# Generated by Django 3.1.4 on 2021-03-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('is_Paid', models.BooleanField(db_index=True, default=False)),
                ('is_Delivered', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Paid_at', models.DateTimeField(auto_now=True)),
                ('Delivered_at', models.DateTimeField(auto_now=True)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_file', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('Shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Post_code', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.ImageField(upload_to='uploads/')),
                ('brand', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('countInStock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.product_category')),
            ],
        ),
    ]
